.\" (c) 2014, 2015 Richard Kettlewell
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.TH anagrams 1
.SH NAME
anagrams \- list multi-word anagrams of any word
.SH SYNOPSIS
.B anagrams
.RI [ options ]
.RB [ -- ]
.RI [ words ...]
.SH DESCRIPTION
.B anagrams
lists all the anagrams it can find of the words listed on the command
line, or read from standard input if none are listed.  Anagrams that
use the same words in different orders are only given once, with the
words in the same order as they appear in the word list itself.
.SH OPTIONS
.TP
\fB-w\fR \fIpath\fR, \fB--wordlist\fR \fIpath\fR
Specify a word list to use.  This should consist of a list of words
one to a line, and nothing else.
.IP
You may specify multiple word lists by using this option multiple
times.  If you do not specify any then a default word list is used.
.TP
\fB-e\fR \fIword\fR, \fB--word\fR \fIword\fR
Add a word to the word list.
.IP
This option does not prevent the default word list from being used.
If you just want to specify words with \fB--word\fR and not use any
word list file, use \fB--wordlist /dev/null\fR.
.TP
\fB-f\fR \fIREGEX\fR, \fB--filter\fR \fIREGEX\fR
Filters any words matching \fIREGEX\fR out of any subsequent word lists
loaded.
This doesn't affect the \fB--word\fR option.
.TP
\fB-h\fR, \fB--help\fR
Show summary of options.
.TP
\fB-V\fR, \fB--version\fR
Show version of program.
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>.
