.\" (c) 2014 Richard Kettlewell
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.TH run-as 1
.SH NAME
run-as \- run a command as a specified user
.SH SYNOPSIS
.B run-as
.RI [ options ]
.RB --
.I user
.RI [ group ]
.B --
.IR command ...
.SH DESCRIPTION
\fBrun-as\fR runs a command as a specified user.
.PP
If only \fIuser\fR is specified then the default group for that user
is assumed.  If \fIgroup\fR is specified as well then that group is
used.
.SH OPTIONS
.TP
\fB-r\fR \fIdirectory\fR, \fB--root\fR \fIdirectory\fR
Alter the root directory before changing user.
.TP
\fB-h\fR, \fB--help\fR
Show summary of options.
.TP
\fB-V\fR, \fB--version\fR
Show version of program.
.SH NOTES
The \fB--\fR arguments separating the options from the user and the
user (and group) from the command are mandatory.
.PP
Although it would seem more logical to have separate programs for
changing user and changing root directory, this can't be done.  If it
were done in separate programs then the change root program wouldn't
work if the change user program had already been run (since only
privileged users can change the root directory of a process).  On the
other hand if the change root program were run first, the change user
program would no longer have access to the files necessary to look up
the user information.
.PP
If \fB--root\fR is used, then the command must be available inside the
chroot.  If this is a problem then you must write your program to
start as a privileged user and change its root directory and UID
itself.
.SH "SEE ALSO"
.BR chroot (2)
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>
