#! /bin/sh
# 
# This file is part of rjkshelltools
# Copyright (C) 2002, 2003, 2009, 2013, 2014 Richard Kettlewell
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 

# exit if something goes wrong
set -e

# test utilities
. ${srcdir:-.}/tests.sh

cat > words <<EOF
bar
boo
far
foo
EOF

testing "anagrams generates all the anagrams implied by a word list"
anagrams -w words -- foobar > output
cat > expected <<EOF
foobar
 bar foo
 boo far
EOF
 
if diff expected output > /dev/null; then
  ok
else
  fail "output did not match what we expected"
  set +e; diff -u expected output >> errors; set -e
fi

testing "anagrams -e works"
anagrams -e bar -e boo -e far -e foo -w /dev/null -- foobar > output
cat > expected <<EOF
foobar
 bar foo
 boo far
EOF
 
if diff expected output > /dev/null; then
  ok
else
  fail "output did not match what we expected"
  set +e; diff -u expected output >> errors; set -e
fi

finished
