#! /bin/sh
# 
# This file is part of rjkshelltools
# Copyright (C) 2001-2003, 2013, 2014 Richard Kettlewell
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# exit if something goes wrong
set -e

# test utilities
. ${srcdir:-.}/tests.sh

testing "pidfile works"
pidfile -- pidfile.pid sh -c '
  echo $$ > command.pid
'
if test ! -f pidfile.pid; then
  fail "pidfile.pid does not exist"
elif test ! -f command.pid; then
  fail "command.pid does not exist"
  fail
else
  read p < pidfile.pid
  read c < command.pid
  if test "x$p" != "x$c"; then
    fail "p=\"$p\", c=\"$c\""
  else
    ok
  fi
fi

finished
