#! /bin/sh
# 
# This file is part of rjkshelltools
# Copyright (C) 2014 Richard Kettlewell
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# exit if something goes wrong
set -e

if tty >/dev/null; then

  # test utilities
  . ${srcdir:-.}/tests.sh

  pwd=`pwd`

  testing "daemonized processes don't have a controlling terminal"
  rm -f pipe
  mkfifo pipe
  daemon -C -- sh -c "
    set +e
    read x < /dev/tty
    echo \$? > pipe
  "
  read status < pipe
  if test "x$status" = x0; then
    fail "read from /dev/tty succeeded when it should have failed"
  else
    ok
  fi

  testing "daemonized processes can't pick up a controlling terminal"
  rm -f pipe
  mkfifo pipe
  mytty=`tty`
  daemon -C -- sh -c "
    set +e
    exec < $mytty
    read x < /dev/tty
    echo \$? > pipe
  "
  read status < pipe
  if test "x$status" = x0; then
    fail "read from /dev/tty succeeded when it should have failed"
  else
    ok
  fi

  finished

else

  echo "(no tty, cannot run these tests)"
  exit 77

fi
